import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FilmsProvider } from "./context/FilmsContext";
import { getGlobalCachedFilms } from "./utils/filmsCache";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Load films once on app startup and pass to context
  const initialFilms = await getGlobalCachedFilms();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FilmsProvider initialFilms={initialFilms}>
          {children}
        </FilmsProvider>
      </body>
    </html>
  );
}
